version: 1
policy:
  pullRequests: collaborators
tasks:
  $match:
    (tasks_for == "github-push"):
      taskId:
        $eval: as_slugid("pr_task")
      provisionerId: "aax{$eval: 'len([1, 2, 3])'}"
      workerType: github-worker
      deadline: {$fromNow: '24 hours'}
      payload:
        maxRunTime: 3600
        image: python
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            /bin/true
      metadata:
        name: test
        description: test
        owner:
          $let:
            lengthMail: {$eval: 'len([1, 2, 3])'}
            typeMail: "${typeof('abc')}"
            #{$eval: 'typeof("${event.pusher.email}")'} 
          in:          
            $if: '"${lengthMail}" == "3"'
            then: bad
            else: ${event.sender.login}@users.noreply.github.com
        source: '${event.repository.url}'
