version: 1
policy:
  pullRequests: collaborators
tasks:
  $match:
    (tasks_for == "github-push"):
      taskId:
        $eval: as_slugid("pr_task")
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      deadline: {$fromNow: '24 hours'}
      payload:
        maxRunTime: 3600
        image: python
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            /bin/true
      metadata:
        name: test
        description: test
        owner:
          $let:
            lengthMail: {$eval: 'len([1, 2, 3]) > 2'}
            typeMail: {$eval: 'typeof(event.pusher.email)'} 
          in:          
            $if: '"${lengthMail}" == "true" && "string" == "${typeMail}" && "@" in event.pusher.email'
            then: bad
            else: ${event.sender.login}@users.noreply.github.com
        source: '${event.repository.url}'
